server:
  port: 7001

eureka:
  instance:
    hostname: localhost #eureka 实例的服务名称
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false #表示自己就是注册中心 职责是维护服务实例，并不需要去检索服务
    serviceUrl:
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置eureka server交互的地址，查询服务和注册服务的依赖地址
  # server:
  #   enable-self-preservation: false 禁用eureka的自我保护机制，不推荐该配置
